//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.WPF.Client.Properties {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MES.WPF.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to wts.ItemName.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ShellGoBackButton.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ShellHamburgerButtonName.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to BusyIndicator.
        /// </summary>
        public static string ShellBusyIndicatorPage {
            get {
                return ResourceManager.GetString("ShellBusyIndicatorPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to PivotGrid.
        /// </summary>
        public static string ShellPivotGridPage {
            get {
                return ResourceManager.GetString("ShellPivotGridPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to PropertyGrid.
        /// </summary>
        public static string ShellPropertyGridPage {
            get {
                return ResourceManager.GetString("ShellPropertyGridPage", resourceCulture);
            }
        }
    
        /// <summary>
            ///   Looks up a localized string similar to Settings page placeholder text.  Your app description goes here..
            /// </summary>
            public static string SettingsPageAboutText {
                get {
                    return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to About this application.
            /// </summary>
            public static string SettingsPageAboutTitle {
                get {
                    return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Choose Theme.
            /// </summary>
            public static string SettingsPageChooseThemeText {
                get {
                    return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Personalization.
            /// </summary>
            public static string SettingsPagePersonalizationTitle {
                get {
                    return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Privacy Statement.
            /// </summary>
            public static string SettingsPagePrivacyStatementText {
                get {
                    return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
                }
            }
    
           
    
            
    		 public static string SettingsPageRadioButtonMaterialDarkBlueTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonMaterialDarkBlueTheme", resourceCulture);
                }
            }
            
            /// <summary>
            ///   Looks up a localized string similar to MaterialDark.
            /// </summary>
            public static string SettingsPageRadioButtonMaterialDarkTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonMaterialDarkTheme", resourceCulture);
                }
            }
            
            /// <summary>
            ///   Looks up a localized string similar to MaterialLightBlue.
            /// </summary>
            public static string SettingsPageRadioButtonMaterialLightBlueTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonMaterialLightBlueTheme", resourceCulture);
                }
            }
            
            /// <summary>
            ///   Looks up a localized string similar to MaterialLight.
            /// </summary>
            public static string SettingsPageRadioButtonMaterialLightTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonMaterialLightTheme", resourceCulture);
                }
            }
            
            /// <summary>
            ///   Looks up a localized string similar to Office2019Black.
            /// </summary>
            public static string SettingsPageRadioButtonOffice2019BlackTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonOffice2019BlackTheme", resourceCulture);
                }
            }
            
            /// <summary>
            ///   Looks up a localized string similar to Office2019Colorful.
            /// </summary>
            public static string SettingsPageRadioButtonOffice2019ColorfulTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonOffice2019ColorfulTheme", resourceCulture);
                }
            }
            
            /// <summary>
            ///   Looks up a localized string similar to Office2019DarkGray.
            /// </summary>
            public static string SettingsPageRadioButtonOffice2019DarkGrayTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonOffice2019DarkGrayTheme", resourceCulture);
                }
            }
            
            /// <summary>
            ///   Looks up a localized string similar to Office2019HighContrast.
            /// </summary>
            public static string SettingsPageRadioButtonOffice2019HighContrastTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonOffice2019HighContrastTheme", resourceCulture);
                }
            }
            
            /// <summary>
            ///   Looks up a localized string similar to Office2019White.
            /// </summary>
            public static string SettingsPageRadioButtonOffice2019WhiteTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonOffice2019WhiteTheme", resourceCulture);
                }
            }
    
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to TileView.
        /// </summary>
        public static string ShellTileViewPage {
            get {
                return ResourceManager.GetString("ShellTileViewPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to TreeGrid.
        /// </summary>
        public static string ShellTreeGridPage {
            get {
                return ResourceManager.GetString("ShellTreeGridPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to TreeView.
        /// </summary>
        public static string ShellTreeViewPage {
            get {
                return ResourceManager.GetString("ShellTreeViewPage", resourceCulture);
            }
        }
    }
}
